# ---- Builder ----
    FROM rust:1-bookworm AS builder
    WORKDIR /usr/src/app
    
    COPY Cargo.toml ./
    COPY src ./src
    COPY migrations* ./migrations/
    RUN cargo build --release
    
    # ---- Production ----
    FROM debian:bookworm-slim
    RUN apt-get update -y && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
    WORKDIR /usr/src/app
    
    COPY --from=builder /usr/src/app/target/release/app ./
    COPY --from=builder /usr/src/app/migrations ./migrations
    
    EXPOSE {{appPort}}
    CMD ["./app"]
    